/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '26/01/17 10:17' with Gradle 2.13
 *
 * @author mati, @date 26/01/17 10:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
